# Generated by Django 2.2.2 on 2019-06-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Source Title', max_length=100, verbose_name='Source Title')),
            ],
            options={
                'db_table': 'table1',
            },
        ),
    ]
